"""
Pure CSS template for GlassForge CLI.

Generates a complete CSS file with liquid glass classes and CSS custom
properties, ready to be included in any web project.
"""

from typing import Dict, Any

from .base import BaseTemplate


class CSSTemplate(BaseTemplate):
    """Template that generates pure CSS with liquid glass effect classes."""

    def render(self, config: Dict[str, Any]) -> str:
        """Render a complete CSS file with liquid glass styles.

        The output includes:
        - CSS custom properties on :root
        - Base .liquid-glass class
        - Hover state styles
        - Shimmer and glow animations
        - Dark mode adaptation
        - Utility modifier classes

        Args:
            config: Engine configuration dictionary.

        Returns:
            Complete CSS string.
        """
        css_vars = self._render_css_variables(config)
        base_class = self._render_base_class(config)
        hover_class = self._render_hover_class(config)
        animation = self._render_animation(config)
        dark_mode = self._render_dark_mode(config)
        modifiers = self._render_modifiers(config)

        parts = [
            f"/* ============================================\n"
            f" * Liquid Glass CSS\n"
            f" * Generated by GlassForge CLI\n"
            f" * Theme: {config.get('name', 'Custom')}\n"
            f" * ============================================ */\n",
            css_vars,
            "",
            base_class,
            "",
            hover_class,
            "",
            animation,
            "",
            dark_mode,
            "",
            modifiers,
        ]

        return "\n".join(parts)

    def _render_css_variables(self, config: Dict[str, Any]) -> str:
        """Render CSS custom properties block."""
        lines = [
            ":root {",
            f"  --glass-blur: {config['blur']}px;",
            f"  --glass-opacity: {config['opacity']};",
            f"  --glass-saturate: {config['saturate']};",
            f"  --glass-border-radius: {config['border_radius']}px;",
            f"  --glass-primary: {config['primary_color']};",
            f"  --glass-secondary: {config.get('secondary_color', config['primary_color'])};",
            f"  --glass-text-color: {config['text_color']};",
            f"  --glass-background: {config['background']};",
            f"  --glass-border: {config['border']};",
            f"  --glass-box-shadow: {config['box_shadow']};",
            f"  --glass-backdrop-filter: {config['backdrop_filter']};",
            f"  --glass-hover-scale: {config['hover_scale']};",
            f"  --glass-gloss: {config['gloss']};",
            "}",
        ]
        return "\n".join(lines)

    def _render_base_class(self, config: Dict[str, Any]) -> str:
        """Render the base .liquid-glass class."""
        lines = [
            ".liquid-glass {",
            f"  /* Backdrop filter for frosted glass effect */",
            f"  -webkit-backdrop-filter: {config['webkit_backdrop_filter']};",
            f"  backdrop-filter: {config['backdrop_filter']};",
            "",
            f"  /* Glass background with light refraction gradient */",
            f"  background: {config['background']};",
            "",
            f"  /* Glass edge highlight */",
            f"  border: {config['border']};",
            "",
            f"  /* Rounded corners */",
            f"  border-radius: {config['border_radius']}px;",
            "",
            f"  /* Multi-layer shadow for depth and gloss */",
            f"  box-shadow: {config['box_shadow']};",
            "",
            f"  /* Text color */",
            f"  color: var(--glass-text-color);",
            "",
            f"  /* Smooth transitions */",
            f"  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);",
            "",
            f"  /* Ensure content sits above backdrop */",
            f"  position: relative;",
            f"  z-index: 1;",
            "}",
        ]
        return "\n".join(lines)

    def _render_hover_class(self, config: Dict[str, Any]) -> str:
        """Render hover state styles."""
        lines = [
            ".liquid-glass:hover {",
            f"  background: {config['hover_background']};",
            f"  box-shadow: {config['hover_box_shadow']};",
            f"  transform: scale({config['hover_scale']});",
            f"  border-color: {config.get('primary_color', '#ffffff')};",
            "}",
        ]
        return "\n".join(lines)

    def _render_animation(self, config: Dict[str, Any]) -> str:
        """Render animation keyframes."""
        return (
            "/* Shimmer animation for dynamic light effect */\n"
            "@keyframes glassShimmer {\n"
            "  0% {\n"
            "    background-position: -200% center;\n"
            "    opacity: 0.8;\n"
            "  }\n"
            "  50% {\n"
            "    opacity: 1;\n"
            "  }\n"
            "  100% {\n"
            "    background-position: 200% center;\n"
            "    opacity: 0.8;\n"
            "  }\n"
            "}\n"
            "\n"
            "/* Glow pulse animation */\n"
            "@keyframes glassGlow {\n"
            "  0%, 100% {\n"
            f"    box-shadow: {config['box_shadow']};\n"
            "  }\n"
            "  50% {\n"
            f"    box-shadow: {config['hover_box_shadow']};\n"
            "  }\n"
            "}\n"
            "\n"
            ".liquid-glass--animated {\n"
            "  animation: glassGlow 3s ease-in-out infinite;\n"
            "}\n"
        )

    def _render_dark_mode(self, config: Dict[str, Any]) -> str:
        """Render dark mode adaptation rules."""
        return (
            "/* Dark mode adaptation */\n"
            "@media (prefers-color-scheme: dark) {\n"
            "  .liquid-glass {\n"
            f"    background: {config['dark_mode_overlay']};\n"
            "    color: #e0e0e0;\n"
            "    border-color: rgba(255, 255, 255, 0.15);\n"
            "  }\n"
            "\n"
            "  .liquid-glass:hover {\n"
            "    border-color: rgba(255, 255, 255, 0.25);\n"
            "  }\n"
            "}\n"
        )

    def _render_modifiers(self, config: Dict[str, Any]) -> str:
        """Render utility modifier classes."""
        return (
            "/* Modifier: Intensify glass effect */\n"
            ".liquid-glass--intense {\n"
            f"  -webkit-backdrop-filter: blur({config['blur'] + 10}px) saturate({config['saturate'] + 0.5});\n"
            f"  backdrop-filter: blur({config['blur'] + 10}px) saturate({config['saturate'] + 0.5});\n"
            "}\n"
            "\n"
            "/* Modifier: Subtle glass effect */\n"
            ".liquid-glass--subtle {\n"
            f"  -webkit-backdrop-filter: blur({max(config['blur'] - 5, 2)}px) saturate({max(config['saturate'] - 0.3, 1.0)});\n"
            f"  backdrop-filter: blur({max(config['blur'] - 5, 2)}px) saturate({max(config['saturate'] - 0.3, 1.0)});\n"
            "}\n"
            "\n"
            "/* Modifier: No blur (transparent only) */\n"
            ".liquid-glass--flat {\n"
            "  -webkit-backdrop-filter: none;\n"
            "  backdrop-filter: none;\n"
            "}\n"
            "\n"
            "/* Modifier: Card variant with padding */\n"
            ".liquid-glass--card {\n"
            "  padding: 24px;\n"
            "}\n"
            "\n"
            "/* Modifier: Button variant */\n"
            ".liquid-glass--button {\n"
            "  padding: 12px 24px;\n"
            "  cursor: pointer;\n"
            "  display: inline-block;\n"
            "  text-decoration: none;\n"
            "  font-weight: 500;\n"
            "}\n"
        )

    def file_extension(self) -> str:
        return ".css"

    def description(self) -> str:
        return "Pure CSS with liquid glass classes and CSS custom properties"
