"""
HTML template for GlassForge CLI.

Generates a complete, self-contained HTML page that demonstrates the
liquid glass effect with multiple card layouts and interactive elements.
"""

from typing import Dict, Any

from .base import BaseTemplate


class HTMLTemplate(BaseTemplate):
    """Template that generates a complete HTML demo page."""

    def render(self, config: Dict[str, Any]) -> str:
        """Render a complete HTML page with liquid glass demo.

        The page includes:
        - A gradient background
        - Multiple glass cards demonstrating different variants
        - Interactive hover effects
        - Dark mode support
        - Responsive layout

        Args:
            config: Engine configuration dictionary.

        Returns:
            Complete HTML string.
        """
        head = self._render_head(config)
        body = self._render_body(config)

        return f"<!DOCTYPE html>\n<html lang=\"en\">\n{head}\n{body}\n</html>"

    def _render_head(self, config: Dict[str, Any]) -> str:
        """Render the HTML head section."""
        return (
            "<head>\n"
            '  <meta charset="UTF-8">\n'
            '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
            "  <title>Liquid Glass Demo - GlassForge</title>\n"
            "  <style>\n"
            f"    {self._render_page_css(config)}\n"
            "  </style>\n"
            "</head>"
        )

    def _render_body(self, config: Dict[str, Any]) -> str:
        """Render the HTML body section."""
        return (
            "<body>\n"
            "  <div class=\"demo-container\">\n"
            "    <header class=\"demo-header\">\n"
            '      <h1 class="liquid-glass liquid-glass--card">Liquid Glass</h1>\n'
            f"      <p class=\"liquid-glass\">Theme: {config.get('name', 'Custom')} | "
            f"Generated by GlassForge CLI</p>\n"
            "    </header>\n"
            "\n"
            '    <section class="demo-grid">\n'
            "      <!-- Card 1: Basic -->\n"
            '      <div class="liquid-glass liquid-glass--card demo-card">\n'
            '        <h2>Basic Card</h2>\n'
            "        <p>A simple liquid glass card with frosted backdrop.</p>\n"
            "      </div>\n"
            "\n"
            "      <!-- Card 2: With content -->\n"
            '      <div class="liquid-glass liquid-glass--card demo-card">\n'
            '        <h2>Content Card</h2>\n'
            "        <p>This card demonstrates text readability on glass.</p>\n"
            '        <div class="demo-tags">\n'
            '          <span class="liquid-glass liquid-glass--button">Tag 1</span>\n'
            '          <span class="liquid-glass liquid-glass--button">Tag 2</span>\n'
            '          <span class="liquid-glass liquid-glass--button">Tag 3</span>\n'
            "        </div>\n"
            "      </div>\n"
            "\n"
            "      <!-- Card 3: Animated -->\n"
            '      <div class="liquid-glass liquid-glass--card liquid-glass--animated demo-card">\n'
            '        <h2>Animated Card</h2>\n'
            "        <p>This card has a pulsing glow animation.</p>\n"
            "      </div>\n"
            "\n"
            "      <!-- Card 4: Intense -->\n"
            '      <div class="liquid-glass liquid-glass--card liquid-glass--intense demo-card">\n'
            '        <h2>Intense Effect</h2>\n'
            "        <p>Stronger blur and saturation for a deeper glass look.</p>\n"
            "      </div>\n"
            "\n"
            "      <!-- Card 5: Stats -->\n"
            '      <div class="liquid-glass liquid-glass--card demo-card demo-card--wide">\n'
            '        <h2>Statistics</h2>\n'
            '        <div class="demo-stats">\n'
            '          <div class="demo-stat">\n'
            "            <span class=\"demo-stat-value\">{blur}</span>\n"
            "            <span class=\"demo-stat-label\">Blur (px)</span>\n"
            "          </div>\n"
            '          <div class="demo-stat">\n'
            "            <span class=\"demo-stat-value\">{opacity}</span>\n"
            "            <span class=\"demo-stat-label\">Opacity</span>\n"
            "          </div>\n"
            '          <div class="demo-stat">\n'
            "            <span class=\"demo-stat-value\">{radius}</span>\n"
            "            <span class=\"demo-stat-label\">Radius (px)</span>\n"
            "          </div>\n"
            '          <div class="demo-stat">\n'
            "            <span class=\"demo-stat-value\">{gloss}</span>\n"
            "            <span class=\"demo-stat-label\">Gloss</span>\n"
            "          </div>\n"
            "        </div>\n"
            "      </div>\n"
            "\n"
            "      <!-- Card 6: Form -->\n"
            '      <div class="liquid-glass liquid-glass--card demo-card">\n'
            '        <h2>Form Elements</h2>\n'
            '        <div class="demo-form">\n'
            '          <input type="text" class="liquid-glass" placeholder="Glass input...">\n'
            '          <button class="liquid-glass liquid-glass--button">Submit</button>\n'
            "        </div>\n"
            "      </div>\n"
            "    </section>\n"
            "  </div>\n"
            "</body>"
        ).format(
            blur=config["blur"],
            opacity=config["opacity"],
            radius=config["border_radius"],
            gloss=config["gloss"],
        )

    def _render_page_css(self, config: Dict[str, Any]) -> str:
        """Render all CSS for the demo page."""
        # Import CSS template content inline
        from .css import CSSTemplate
        css_template = CSSTemplate()
        glass_css = css_template.render(config)

        # Add page-specific styles
        page_css = (
            "\n\n"
            "/* ---- Page Layout ---- */\n"
            "* {\n"
            "  margin: 0;\n"
            "  padding: 0;\n"
            "  box-sizing: border-box;\n"
            "}\n"
            "\n"
            "body {\n"
            f"  background: {config.get('background_gradient', 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)')};\n"
            "  min-height: 100vh;\n"
            "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n"
            "    'Helvetica Neue', Arial, sans-serif;\n"
            "  color: #fff;\n"
            "  padding: 40px 20px;\n"
            "}\n"
            "\n"
            ".demo-container {\n"
            "  max-width: 1200px;\n"
            "  margin: 0 auto;\n"
            "}\n"
            "\n"
            ".demo-header {\n"
            "  text-align: center;\n"
            "  margin-bottom: 48px;\n"
            "}\n"
            "\n"
            ".demo-header h1 {\n"
            "  font-size: 3rem;\n"
            "  font-weight: 700;\n"
            "  margin-bottom: 12px;\n"
            "  display: inline-block;\n"
            "}\n"
            "\n"
            ".demo-header p {\n"
            "  font-size: 1.1rem;\n"
            "  opacity: 0.8;\n"
            "  display: inline-block;\n"
            "}\n"
            "\n"
            ".demo-grid {\n"
            "  display: grid;\n"
            "  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));\n"
            "  gap: 24px;\n"
            "}\n"
            "\n"
            ".demo-card {\n"
            "  min-height: 200px;\n"
            "}\n"
            "\n"
            ".demo-card--wide {\n"
            "  grid-column: span 2;\n"
            "}\n"
            "\n"
            ".demo-card h2 {\n"
            "  font-size: 1.3rem;\n"
            "  margin-bottom: 12px;\n"
            "  font-weight: 600;\n"
            "}\n"
            "\n"
            ".demo-card p {\n"
            "  opacity: 0.85;\n"
            "  line-height: 1.6;\n"
            "}\n"
            "\n"
            ".demo-tags {\n"
            "  display: flex;\n"
            "  gap: 8px;\n"
            "  margin-top: 16px;\n"
            "  flex-wrap: wrap;\n"
            "}\n"
            "\n"
            ".demo-stats {\n"
            "  display: flex;\n"
            "  justify-content: space-around;\n"
            "  margin-top: 20px;\n"
            "}\n"
            "\n"
            ".demo-stat {\n"
            "  text-align: center;\n"
            "}\n"
            "\n"
            ".demo-stat-value {\n"
            "  display: block;\n"
            "  font-size: 2rem;\n"
            "  font-weight: 700;\n"
            "}\n"
            "\n"
            ".demo-stat-label {\n"
            "  font-size: 0.85rem;\n"
            "  opacity: 0.7;\n"
            "}\n"
            "\n"
            ".demo-form {\n"
            "  display: flex;\n"
            "  flex-direction: column;\n"
            "  gap: 12px;\n"
            "  margin-top: 12px;\n"
            "}\n"
            "\n"
            ".demo-form input {\n"
            "  padding: 12px 16px;\n"
            "  border: none;\n"
            "  outline: none;\n"
            "  font-size: 1rem;\n"
            "  color: inherit;\n"
            "  width: 100%;\n"
            "}\n"
            "\n"
            ".demo-form input::placeholder {\n"
            "  opacity: 0.5;\n"
            "}\n"
            "\n"
            "/* Responsive */\n"
            "@media (max-width: 768px) {\n"
            "  .demo-card--wide {\n"
            "    grid-column: span 1;\n"
            "  }\n"
            "\n"
            "  .demo-header h1 {\n"
            "    font-size: 2rem;\n"
            "  }\n"
            "\n"
            "  .demo-stats {\n"
            "    flex-wrap: wrap;\n"
            "    gap: 16px;\n"
            "  }\n"
            "}\n"
        )

        return glass_css + page_css

    def file_extension(self) -> str:
        return ".html"

    def description(self) -> str:
        return "Complete HTML page with liquid glass demo cards"
