"""
React component template for GlassForge CLI.

Generates a TypeScript React component with props for customizing
the liquid glass effect.
"""

from typing import Dict, Any

from .base import BaseTemplate


class ReactTemplate(BaseTemplate):
    """Template that generates a TypeScript React component with liquid glass effect."""

    def render(self, config: Dict[str, Any]) -> str:
        """Render a complete React TypeScript component.

        Args:
            config: Engine configuration dictionary.

        Returns:
            Complete React component code string.
        """
        props_interface = self._render_props_interface(config)
        component = self._render_component(config)
        css_module = self._render_css_module(config)
        usage_example = self._render_usage_example(config)

        parts = [
            "/**\n"
            f" * LiquidGlass Component\n"
            f" * Generated by GlassForge CLI\n"
            f" * Theme: {config.get('name', 'Custom')}\n"
            " *\n"
            " * A React component that renders a liquid glass effect container.\n"
            " */\n",
            "",
            "import React from 'react';\n",
            "",
            props_interface,
            "",
            component,
            "",
            "/* ---- Inline styles module ---- */\n",
            css_module,
            "",
            "/* ---- Usage Example ---- */\n",
            usage_example,
        ]

        return "\n".join(parts)

    def _render_props_interface(self, config: Dict[str, Any]) -> str:
        """Render the TypeScript props interface."""
        blur = config["blur"]
        opacity = config["opacity"]
        radius = config["border_radius"]

        lines = [
            "interface LiquidGlassProps {",
            "  /** Child elements to render inside the glass container */",
            "  children: React.ReactNode;",
            "  /** Additional CSS class names */",
            "  className?: string;",
            "  /** Inline style overrides */",
            "  style?: React.CSSProperties;",
            f"  /** Blur intensity in pixels (default: {blur}) */",
            "  blur?: number;",
            f"  /** Background opacity (0-1, default: {opacity}) */",
            "  opacity?: number;",
            f"  /** Border radius in pixels (default: {radius}) */",
            "  borderRadius?: number;",
            "  /** Whether to enable hover animation (default: true) */",
            "  hover?: boolean;",
            "  /** Whether to enable glow animation (default: false) */",
            "  animated?: boolean;",
            "  /** HTML tag to render (default: 'div') */",
            "  as?: keyof JSX.IntrinsicElements;",
            "  /** Click handler */",
            "  onClick?: () => void;",
            "}",
        ]
        return "\n".join(lines)

    def _render_component(self, config: Dict[str, Any]) -> str:
        """Render the React component function."""
        blur = config["blur"]
        opacity = config["opacity"]
        radius = config["border_radius"]
        saturate = config["saturate"]
        background = config["background"]
        border = config["border"]
        box_shadow = config["box_shadow"]
        text_color = config["text_color"]
        hover_bg = config["hover_background"]
        hover_shadow = config["hover_box_shadow"]
        scale = config["hover_scale"]

        # Build the className line as a plain string to avoid f-string escaping issues
        class_name_line = (
            "      className={`liquid-glass ${animated ? 'liquid-glass--animated' : ''} ${className}`}"
        )

        lines = [
            "const LiquidGlass: React.FC<LiquidGlassProps> = ({",
            "  children,",
            "  className = '',",
            "  style = {},",
            "  blur,",
            "  opacity,",
            "  borderRadius,",
            "  hover = true,",
            "  animated = false,",
            "  as: Tag = 'div',",
            "  onClick,",
            "}) => {",
            f"  const blurValue = blur ?? {blur};",
            f"  const opacityValue = opacity ?? {opacity};",
            f"  const radiusValue = borderRadius ?? {radius};",
            "",
            "  const glassStyle: React.CSSProperties = {",
            f"    WebkitBackdropFilter: `blur(${'{blurValue}'}px) saturate({saturate})`,",
            f"    backdropFilter: `blur(${'{blurValue}'}px) saturate({saturate})`,",
            f"    background: '{background}',",
            f"    border: '{border}',",
            f"    borderRadius: `${'{radiusValue}'}px`,",
            f"    boxShadow: '{box_shadow}',",
            f"    color: '{text_color}',",
            "    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',",
            "    position: 'relative',",
            "    zIndex: 1,",
            "    ...style,",
            "  };",
            "",
            "  const hoverStyle: React.CSSProperties = hover",
            "    ? {",
            f"        background: '{hover_bg}',",
            f"        boxShadow: '{hover_shadow}',",
            f"        transform: 'scale({scale})',",
            "      }",
            "    : {};",
            "",
            "  const [isHovered, setIsHovered] = React.useState(false);",
            "",
            "  return (",
            "    <Tag",
            class_name_line,
            "      style={{ ...glassStyle, ...(isHovered ? hoverStyle : {}) }}",
            "      onMouseEnter={() => setIsHovered(true)}",
            "      onMouseLeave={() => setIsHovered(false)}",
            "      onClick={onClick}",
            "    >",
            "      {children}",
            "    </Tag>",
            "  );",
            "};",
            "",
            "export default LiquidGlass;",
        ]
        return "\n".join(lines)

    def _render_css_module(self, config: Dict[str, Any]) -> str:
        """Render accompanying CSS for animations."""
        box_shadow = config["box_shadow"]
        hover_shadow = config["hover_box_shadow"]

        lines = [
            "/* Include this CSS in your global styles or a CSS module */",
            "/*",
            "@keyframes glassGlow {",
            "  0%, 100% {",
            f"    box-shadow: {box_shadow};",
            "  }",
            "  50% {",
            f"    box-shadow: {hover_shadow};",
            "  }",
            "}",
            "",
            ".liquid-glass--animated {",
            "  animation: glassGlow 3s ease-in-out infinite;",
            "}",
            "*/",
        ]
        return "\n".join(lines)

    def _render_usage_example(self, config: Dict[str, Any]) -> str:
        """Render usage example as a comment."""
        return (
            "// Example usage:\n"
            "//\n"
            "// <LiquidGlass blur={24} borderRadius={28}>\n"
            "//   <h2>Glass Card</h2>\n"
            "//   <p>This content has a liquid glass effect.</p>\n"
            "// </LiquidGlass>\n"
            "//\n"
            "// <LiquidGlass animated hover={false}>\n"
            "//   <button>Click Me</button>\n"
            "// </LiquidGlass>\n"
        )

    def file_extension(self) -> str:
        return ".tsx"

    def description(self) -> str:
        return "TypeScript React component with liquid glass props"
