"""
Svelte component template for GlassForge CLI.

Generates a Svelte component with exported props and scoped CSS
for the liquid glass effect.
"""

from typing import Dict, Any

from .base import BaseTemplate


class SvelteTemplate(BaseTemplate):
    """Template that generates a Svelte component with liquid glass effect."""

    def render(self, config: Dict[str, Any]) -> str:
        """Render a complete Svelte component.

        Args:
            config: Engine configuration dictionary.

        Returns:
            Complete Svelte component code string.
        """
        script_section = self._render_script(config)
        template_section = self._render_template(config)
        style_section = self._render_style(config)

        parts = [
            f"{{!--\n"
            f"  LiquidGlass Component\n"
            f"  Generated by GlassForge CLI\n"
            f"  Theme: {config.get('name', 'Custom')}\n"
            "\n"
            "  A Svelte component that renders a liquid glass effect container.\n"
            "--}}\n",
            "<script>\n",
            script_section,
            "</script>\n",
            "",
            template_section,
            "",
            "<style>\n",
            style_section,
            "</style>",
        ]

        return "\n".join(parts)

    def _render_script(self, config: Dict[str, Any]) -> str:
        """Render the script section with exported props."""
        blur = config["blur"]
        opacity = config["opacity"]
        radius = config["border_radius"]
        saturate = config["saturate"]
        background = config["background"]
        border = config["border"]
        hover_shadow = config["hover_box_shadow"]
        box_shadow = config["box_shadow"]
        text_color = config["text_color"]
        scale = config["hover_scale"]

        lines = [
            "  import { createEventDispatcher } from 'svelte';",
            "",
            "  const dispatch = createEventDispatcher();",
            "",
            "  /** Blur intensity in pixels */",
            f"  export let blur = {blur};",
            "  /** Background opacity (0-1) */",
            f"  export let opacity = {opacity};",
            "  /** Border radius in pixels */",
            f"  export let borderRadius = {radius};",
            "  /** Enable hover effect */",
            "  export let hover = true;",
            "  /** Enable glow animation */",
            "  export let animated = false;",
            "  /** HTML tag to render */",
            "  export let tag = 'div';",
            "",
            "  let isHovered = false;",
            "",
            "  $: glassStyle = {",
            f"    WebkitBackdropFilter: `blur(${{blur}}px) saturate({saturate})`,",
            f"    backdropFilter: `blur(${{blur}}px) saturate({saturate})`,",
            f"    background: '{background}',",
            f"    border: '{border}',",
            f"    borderRadius: `${{borderRadius}}px`,",
            "    boxShadow: isHovered && hover",
            f"      ? '{hover_shadow}'",
            f"      : '{box_shadow}',",
            f"    color: '{text_color}',",
            "    transform: isHovered && hover",
            f"      ? 'scale({scale})'",
            "      : 'scale(1)',",
            "    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',",
            "    position: 'relative',",
            "    zIndex: 1,",
            "  };",
            "",
            "  function handleClick() {",
            "    dispatch('click');",
            "  }",
        ]
        return "\n".join(lines)

    def _render_template(self, config: Dict[str, Any]) -> str:
        """Render the HTML template section."""
        return (
            "{#if tag === 'button'}\n"
            "  <button\n"
            '    class="liquid-glass"\n'
            "    class:animated={animated}\n"
            "    style={glassStyle}\n"
            "    on:mouseenter={() => isHovered = true}\n"
            "    on:mouseleave={() => isHovered = false}\n"
            "    on:click={handleClick}\n"
            "  >\n"
            "    <slot />\n"
            "  </button>\n"
            "{:else}\n"
            "  {#if tag === 'a'}\n"
            "    <a\n"
            '      class="liquid-glass"\n'
            "      class:animated={animated}\n"
            "      style={glassStyle}\n"
            "      on:mouseenter={() => isHovered = true}\n"
            "      on:mouseleave={() => isHovered = false}\n"
            "      on:click={handleClick}\n"
            "    >\n"
            "      <slot />\n"
            "    </a>\n"
            "  {:else}\n"
            "    <div\n"
            '      class="liquid-glass"\n'
            "      class:animated={animated}\n"
            "      style={glassStyle}\n"
            "      on:mouseenter={() => isHovered = true}\n"
            "      on:mouseleave={() => isHovered = false}\n"
            "      on:click={handleClick}\n"
            "    >\n"
            "      <slot />\n"
            "    </div>\n"
            "  {/if}\n"
            "{/if}\n"
        )

    def _render_style(self, config: Dict[str, Any]) -> str:
        """Render the style section."""
        box_shadow = config["box_shadow"]
        hover_shadow = config["hover_box_shadow"]

        lines = [
            ".liquid-glass {",
            "  /* Base styles are applied via reactive style binding */",
            "}",
            "",
            "@keyframes glassGlow {",
            "  0%, 100% {",
            f"    box-shadow: {box_shadow};",
            "  }",
            "  50% {",
            f"    box-shadow: {hover_shadow};",
            "  }",
            "}",
            "",
            ".animated {",
            "  animation: glassGlow 3s ease-in-out infinite;",
            "}",
        ]
        return "\n".join(lines)

    def file_extension(self) -> str:
        return ".svelte"

    def description(self) -> str:
        return "Svelte component with liquid glass props"
