"""
Vue 3 SFC component template for GlassForge CLI.

Generates a Vue 3 Single File Component with props, computed styles,
and scoped CSS for the liquid glass effect.
"""

from typing import Dict, Any

from .base import BaseTemplate


class VueTemplate(BaseTemplate):
    """Template that generates a Vue 3 SFC component with liquid glass effect."""

    def render(self, config: Dict[str, Any]) -> str:
        """Render a complete Vue 3 SFC component.

        Args:
            config: Engine configuration dictionary.

        Returns:
            Complete Vue SFC code string.
        """
        template_section = self._render_template(config)
        script_section = self._render_script(config)
        style_section = self._render_style(config)

        parts = [
            f"<!--\n"
            f"  LiquidGlass Component\n"
            f"  Generated by GlassForge CLI\n"
            f"  Theme: {config.get('name', 'Custom')}\n"
            "\n"
            "  A Vue 3 SFC component that renders a liquid glass effect container.\n"
            "-->\n",
            "<template>\n",
            template_section,
            "</template>\n",
            "",
            "<script setup lang=\"ts\">\n",
            script_section,
            "</script>\n",
            "",
            "<style scoped>\n",
            style_section,
            "</style>",
        ]

        return "\n".join(parts)

    def _render_template(self, config: Dict[str, Any]) -> str:
        """Render the template section."""
        return (
            '  <component\n'
            "    :is=\"tag\"\n"
            '    class="liquid-glass"\n'
            "    :class=\"{\n"
            "      'liquid-glass--hovered': isHovered,\n"
            "      'liquid-glass--animated': animated,\n"
            "    }\"\n"
            "    :style=\"glassStyle\"\n"
            "    @mouseenter=\"isHovered = true\"\n"
            "    @mouseleave=\"isHovered = false\"\n"
            "    @click=\"$emit('click')\"\n"
            "  >\n"
            "    <slot />\n"
            "  </component>\n"
        )

    def _render_script(self, config: Dict[str, Any]) -> str:
        """Render the script setup section."""
        blur = config["blur"]
        opacity = config["opacity"]
        radius = config["border_radius"]
        saturate = config["saturate"]
        background = config["background"]
        border = config["border"]
        hover_shadow = config["hover_box_shadow"]
        box_shadow = config["box_shadow"]
        text_color = config["text_color"]
        scale = config["hover_scale"]

        lines = [
            "import { ref, computed } from 'vue';",
            "",
            "interface Props {",
            "  /** Blur intensity in pixels */",
            f"  blur?: number;  // default: {blur}",
            "  /** Background opacity (0-1) */",
            f"  opacity?: number;  // default: {opacity}",
            "  /** Border radius in pixels */",
            f"  borderRadius?: number;  // default: {radius}",
            "  /** Enable hover effect */",
            "  hover?: boolean;  // default: true",
            "  /** Enable glow animation */",
            "  animated?: boolean;  // default: false",
            "  /** HTML tag to render */",
            "  tag?: string;  // default: 'div'",
            "}",
            "",
            "const props = withDefaults(defineProps<Props>(), {",
            f"  blur: {blur},",
            f"  opacity: {opacity},",
            f"  borderRadius: {radius},",
            "  hover: true,",
            "  animated: false,",
            "  tag: 'div',",
            "});",
            "",
            "defineEmits<{ click: [] }>();",
            "",
            "const isHovered = ref(false);",
            "",
            "const glassStyle = computed(() => ({",
            f"  WebkitBackdropFilter: `blur(${{props.blur}}px) saturate({saturate})`,",
            f"  backdropFilter: `blur(${{props.blur}}px) saturate({saturate})`,",
            f"  background: '{background}',",
            f"  border: '{border}',",
            "  borderRadius: `${{props.borderRadius}}px`,",
            "  boxShadow: isHovered.value && props.hover",
            f"    ? '{hover_shadow}'",
            f"    : '{box_shadow}',",
            f"  color: '{text_color}',",
            "  transform: isHovered.value && props.hover",
            f"    ? 'scale({scale})'",
            "    : 'scale(1)',",
            "  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',",
            "  position: 'relative',",
            "  zIndex: 1,",
            "}));",
        ]
        return "\n".join(lines)

    def _render_style(self, config: Dict[str, Any]) -> str:
        """Render the scoped style section."""
        box_shadow = config["box_shadow"]
        hover_shadow = config["hover_box_shadow"]

        lines = [
            ".liquid-glass {",
            "  /* Base styles are applied via inline computed style */",
            "}",
            "",
            "@keyframes glassGlow {",
            "  0%, 100% {",
            f"    box-shadow: {box_shadow};",
            "  }",
            "  50% {",
            f"    box-shadow: {hover_shadow};",
            "  }",
            "}",
            "",
            ".liquid-glass--animated {",
            "  animation: glassGlow 3s ease-in-out infinite;",
            "}",
        ]
        return "\n".join(lines)

    def file_extension(self) -> str:
        return ".vue"

    def description(self) -> str:
        return "Vue 3 SFC component with liquid glass props"
